// FixMyPDFs service worker 346c31ad0b16. Generated by integrations/service-worker.ts.
const SHELL = 'fmp-shell-346c31ad0b16';
const RUNTIME = 'fmp-runtime-v1';
const PRECACHE = ["/","/offline","/favicon.svg","/manifest.webmanifest","/_astro/Base._35O0XNM.css","/_astro/Base.astro_astro_type_script_index_0_lang.CNTRPNav.js","/_astro/Header.astro_astro_type_script_index_0_lang.DN4EciKt.js","/_astro/HeroPicker.astro_astro_type_script_index_0_lang.D0aETEZi.js","/_astro/SearchDialog.astro_astro_type_script_index_0_lang.01HsQ-Sc.js","/_astro/bytes.KcDjyiEU.js","/_astro/icons.CAYzS_yj.js","/_astro/index.astro_astro_type_script_index_0_lang.ld-EyT2F.js","/_astro/offline.astro_astro_type_script_index_0_lang.mTHzbvRh.js","/_astro/preload-helper.B3nfOi5I.js","/_astro/rolldown-runtime.C0FnF6B9.js","/_astro/slot.CRr8J_Xd.js","/icons-79618dbf99.svg"];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(SHELL).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('fmp-shell-') && k !== SHELL).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Pages: the network first so content stays fresh, then the cached copy, then the offline page.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res.ok) caches.open(RUNTIME).then((c) => c.put(req, res.clone()));
          return res;
        })
        .catch(async () => (await caches.match(req, { ignoreSearch: true })) || (await caches.match('/offline')) || Response.error()),
    );
    return;
  }

  // Hashed build files and versioned engines never change, so the cache wins.
  if (url.pathname.startsWith('/_astro/') || url.pathname.startsWith('/vendor/')) {
    event.respondWith(
      caches.match(req).then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            if (res.ok) caches.open(RUNTIME).then((c) => c.put(req, res.clone()));
            return res;
          }),
      ),
    );
    return;
  }

  // Everything else — the search index, the manifest, sitemaps, icons — network first, cache as the
  // offline fallback. It used to be stale-while-revalidate, which meant the first visit after a deploy
  // got the old copy: after a URL change, that is a search index full of links to pages that moved.
  // These files are small and unhashed, so a fresh fetch costs nothing and a stale one costs a 404.
  event.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok) caches.open(RUNTIME).then((c) => c.put(req, res.clone()));
        return res;
      })
      .catch(async () => (await caches.match(req)) || Response.error()),
  );
});
